version: '3.8'
services:
  minio:
    image: quay.io/minio/minio
    environment:
      - MINIO_DOMAIN=minio
    ports:
      - "9000:9000"
      - "9090:9090"
    command: server /data --console-address ":9090"

  kafka:
    image: "aivenoy/kafka:3.3-2022-10-06-tiered-storage-1-ts-1"
    depends_on:
      - minio
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: "localhost:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,BROKER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,BROKER://kafka:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,BROKER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "BROKER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 10000
      KAFKA_REMOTE_LOG_STORAGE_SYSTEM_ENABLE: true
      KAFKA_REMOTE_LOG_MANAGER_TASK_INTERVAL_MS: 5000
      KAFKA_REMOTE_LOG_METADATA_MANAGER_CLASS_NAME: "org.apache.kafka.server.log.remote.metadata.storage.TopicBasedRemoteLogMetadataManager"
      KAFKA_RLMM_CONFIG_REMOTE_LOG_METADATA_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_REMOTE_LOG_METADATA_MANAGER_LISTENER_NAME: BROKER
      KAFKA_REMOTE_LOG_STORAGE_MANAGER_CLASS_PATH: "/tiered-storage-for-apache-kafka/*"
      KAFKA_REMOTE_LOG_STORAGE_MANAGER_CLASS_NAME: "io.aiven.kafka.tieredstorage.RemoteStorageManager"
      KAFKA_RSM_CONFIG_CHUNK_SIZE: 102400
      KAFKA_RSM_CONFIG_STORAGE_BACKEND_CLASS_NAME: "io.aiven.kafka.tieredstorage.storage.s3.S3Storage"
      KAFKA_RSM_CONFIG_KEY_PREFIX: "tiered-storage-demo/"
      KAFKA_RSM_CONFIG_STORAGE_S3_ENDPOINT_URL: "http://minio:9000"
      KAFKA_RSM_CONFIG_STORAGE_S3_BUCKET_NAME: "test-bucket"
      KAFKA_RSM_CONFIG_STORAGE_S3_REGION: "eu-central-1"
      KAFKA_RSM_CONFIG_STORAGE_S3_PATH_STYLE_ACCESS_ENABLED: "true"
      KAFKA_RSM_CONFIG_STORAGE_AWS_ACCESS_KEY_ID: "minioadmin"
      KAFKA_RSM_CONFIG_STORAGE_AWS_SECRET_ACCESS_KEY: "minioadmin"
    volumes:
      - "./run.sh:/tmp/run.sh"
      - "./local-data:/var/lib/kafka/data"
    command: "/tmp/run.sh"
